### ISSUE TITLE
I can not scroll the grid section to view the third row when I expanded 1200px for a grid row

### ISSUE THREAD

**Issue by gusbemacbe** [Leniolabs/layoutit-grid#68] opened 2021-03-02 04:38 UTC
Hello,

1. Select for 1fr for first grid row.
2. Select for 1200px for second grid row.
3. Select for 300px for third row.
4. Try to scroll the grid section to view the third grid row.

**Comment by matias-capeletto** [comment] 2021-03-02 05:46
Thanks @gusbemacbe, we are going to tackle this one as part of v2 Not too long til it's released :)

**Comment by gusbemacbe** [comment] 2021-04-13 08:49
Any news?

**Comment by patak-js** [comment] 2021-04-13 09:06
Releasing v2 is taking longer than we expected, we want to be careful with changing the app since there is a lot of users right now. But I hope we can release it soon.

**Comment by userquin** [comment] 2021-07-10 14:19
@gusbemacbe since you are using fixed size you also need to increase the `width` on the `Area box` at bottom of left menu. I think what you need, cannot be done here since the `editor area` has a fixed size on screen and so you need to increase the width and/or the height of the `area editor` on `Area box`.

@patak-js maybe we need to add some hint in the docs about using fixed units (px, em, rem missing?) readwhat I've tested.

I'm testing with the width and the heigth configured to `editor area` in the code, since we are setting to `editor area` the configuration provided by the user, we cannot set or remove the width and the height of this `editor area` at the same time.

For example, if I configure `1fr 1200px 300px` to columns specs and remove `width` and `height` in code, then it works with the default width on `Area box` => the scrolls appear and we can see it working. But if I just configure the width to `2000px` just stop working.

![imagen](https://user-images.githubusercontent.com/6311119/125165943-7559d700-e199-11eb-82bc-2afeb2ef8045.png)

![imagen](https://user-images.githubusercontent.com/6311119/125165948-81459900-e199-11eb-8810-1fb61414dc7e.png)

In the other hand, with the provided example, if I configure the width to `2000px`, it works with current code (setting the width and the height properly on `Area box`).

![imagen](https://user-images.githubusercontent.com/6311119/125165972-aafec000-e199-11eb-9d5a-2f96acddf4f1.png)

**Comment by patak-js** [comment] 2021-07-11 12:16
Thanks for digging into this @userquin, I thought there was something broken with the CSS for the editor but you are right here. Looks like we introduced this regression when we start using 100% for the width and height of the main area. This simplified some things but looks like we need to return to the previous values for this to work.
So, probably the best way forward is to set width and height defaulting to "initial", and in the gridAreaStyles use min-height and min-width of 100% if it is initial and then check that the code exports still works as expected. We'll need to check what is better here.

**Comment by patak-js** [comment] 2021-07-22 16:53
This should be fixed now. Deployed to https://grid.layoutit.com (wait for the refresh to see it, and you may have to press reset to make this one work)
Thanks again for the report and for digging into this issue. Let me know if something looks off to you.

**Closed by patak-js** 2021-07-22 16:53 UTC
Labels: bug
